name: AI Issue Summarizer

on:
  issues:
    types: [opened]

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Issue Info
        id: extract
        run: |
          echo "ISSUE_TITLE=${{ github.event.issue.title }}" >> $GITHUB_ENV
          echo "ISSUE_BODY<<EOF" >> $GITHUB_ENV
          echo "${{ github.event.issue.body }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV

      - name: Call OpenAI GPT-4o API
        id: gpt
        run: |
          RESPONSE=$(curl https://api.openai.com/v1/chat/completions \
            -s \
            -H "Authorization: Bearer ${{ secrets.OPENAIAPIKEY }}" \
            -H "Content-Type: application/json" \
            -d @- <<JSON
{
  "model": "gpt-4o",
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful GitHub assistant. Summarize the issue in one paragraph."
    },
    {
      "role": "user",
      "content": "Issue title: $ISSUE_TITLE\n\nIssue body: $ISSUE_BODY"
    }
  ]
}
JSON
          )

          # Safely write multiline summary using heredoc syntax
          {
            echo "SUMMARY<<EOF"
            echo "$RESPONSE"
            echo "EOF"
          } >> $GITHUB_ENV

        env:
          OPENAIAPIKEY: ${{ secrets.OPENAIAPIKEY }}
          ISSUE_TITLE: ${{ env.ISSUE_TITLE }}
          ISSUE_BODY: ${{ env.ISSUE_BODY }}

      - name: Comment on Issue with Summary
        run: |
          gh issue comment "$ISSUE_NUMBER" --body "**🧠 AI Summary:** $SUMMARY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ env.ISSUE_NUMBER }}
          SUMMARY: ${{ env.SUMMARY }}
