name: AI Issue Summarizer

on:
  issues:
    types: [opened]

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      - name: Extract issue info
        id: vars
        run: |
          echo "TITLE=$(echo "${{ github.event.issue.title }}" | sed 's/"/\\"/g')" >> $GITHUB_ENV
          echo "BODY=$(echo "${{ github.event.issue.body }}" | sed 's/"/\\"/g')" >> $GITHUB_ENV
          echo "NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV

      - name: Call OpenAI to summarize
        id: gpt
        run: |
          RESPONSE=$(curl https://api.openai.com/v1/chat/completions \
            -s \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAIAPIKEY }}" \
            -d '{
              "model": "gpt-3.5-turbo",
              "messages": [
                {
                  "role": "system",
                  "content": "You are a helpful assistant that summarizes GitHub issues in one paragraph."
                },
                {
                  "role": "user",
                  "content": "Summarize this issue:\n\nTitle: '${{ env.TITLE }}'\n\nBody: '${{ env.BODY }}'"
                }
              ]
            }' | jq -r '.choices[0].message.content')
          echo "RESPONSE<<EOF" >> $GITHUB_ENV
          echo "$RESPONSE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Post comment to issue
        run: |
          gh issue comment ${{ env.NUMBER }} --body "${{ env.RESPONSE }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
