name: AI Issue Summarizer

on:
  issues:
    types: [opened]

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      - name: Format inputs
        id: vars
        run: |
          echo "TITLE=${{ github.event.issue.title }}" >> $GITHUB_ENV
          echo "BODY=${{ github.event.issue.body }}" >> $GITHUB_ENV
          echo "NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV

      - name: Summarize with OpenAI
        id: gpt
        run: |
          echo "Calling OpenAI..."
          RESPONSE=$(curl https://api.openai.com/v1/chat/completions \
            -s \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAIAPIKEY }}" \
            -d '{
              "model": "gpt-3.5-turbo",
              "messages": [
                {
                  "role": "system",
                  "content": "You are a helpful assistant that summarizes GitHub issues."
                },
                {
                  "role": "user",
                  "content": "Summarize this GitHub issue:\n\nTitle: '${{ env.TITLE }}'\n\nBody: '${{ env.BODY }}'"
                }
              ]
            }' | jq -r '.choices[0].message.content')

          echo "SUMMARY<<EOF" >> $GITHUB_ENV
          echo "$RESPONSE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Post summary comment
        run: |
          echo "Posting comment..."
          gh issue comment ${{ env.NUMBER }} --body "**🧠 AI Summary:** ${{ env.SUMMARY }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
